module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'core',
        'api-gateway',
        'web',
        'mobile',
        'auth',
        'tenants',
        'users',
        'rbac',
        'audit',
        'crm',
        'billing',
        'fiscal',
        'radius',
        'ipam',
        'olt',
        'tr069',
        'ftth',
        'voip',
        'chatbot',
        'ai',
        'inventory',
        'tickets',
        'noc',
        'portal',
        'bi',
        'infra',
        'ci',
        'docs',
        'deps',
      ],
    ],
    'subject-case': [0],
  },
};
